## -----------------------------------------------------------------------------
## SECRET MANAGEMENT
## -----------------------------------------------------------------------------
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.17.3
      helm:
        valueFiles:
          - $values/k8s/sealed-secrets/values.yaml
    - repoURL: https://gitea.k8s.szp.io/tillycode/homelab.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
## -----------------------------------------------------------------------------
## GATEKEEPER
## -----------------------------------------------------------------------------
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
spec:
  project: default
  sources:
    - repoURL: https://gitea.k8s.szp.io/tillycode/homelab.git
      targetRevision: master
      path: k8s/gatekeeper
  destination:
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
