## -----------------------------------------------------------------------------
## KUBEVIRT
## -----------------------------------------------------------------------------
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
spec:
  project: default
  source:
    repoURL: https://gitea.k8s.szp.io/tillycode/homelab.git
    targetRevision: master
    path: k8s/kubevirt
  destination:
    server: https://kubernetes.default.svc
