apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.13/manifests/install.yaml
  - ingress.yaml
  - secrets.yaml

configMapGenerator:
  - name: argocd-tls-certs-cm
    behavior: merge
    files:
      - gitea.k8s.szp.io=../../certs/roots.pem
    options:
      disableNameSuffixHash: true

patches:
  - path: configmaps.yaml
