---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool-auto
  namespace: metallb-system
spec:
  addresses:
    - 10.41.192.0/18
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool-static
  namespace: metallb-system
spec:
  addresses:
    - 10.41.0.0/18
  autoAssign: false
